# -*- coding: utf-8 -*-
"""microsoft_BitNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqT9k-FZzrPlSNFil1Oo3_O7mUuM3cTM
"""





"""https://github.com/microsoft/BitNet"""

# Commented out IPython magic to ensure Python compatibility.
!git clone --recursive https://github.com/microsoft/BitNet.git
# %cd BitNet

!pip install -r requirements.txt

!python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s

# Commented out IPython magic to ensure Python compatibility.
# %cd BitNet
# Run inference with the quantized model
!python /content/BitNet/run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf BitNet  # Clean up in case of a partial or corrupted clone
!git clone --recursive https://github.com/microsoft/BitNet.git
# %cd /content/BitNet

!apt-get update && apt-get install -y clang cmake
!pip install -r requirements.txt

# This configures the kernels, runs CMake, and creates build/bin/llama-cli
!python /content/BitNet/setup_env.py -q i2_s

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

# Ensure the include directory and header exist so CMake won't complain
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# Generate build files and compile llama-cli
!cmake -B build
!cmake --build build --config Release -j$(nproc)

cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
!cmake --build build --config Release -j$(nproc)

!ls /content/BitNet/build/bin

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet
!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

# 1. Ensure required header stub exists
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# 2. Configure CMake with examples/CLI tools enabled
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_TOOLS=ON

# 3. Explicitly build the llama-cli target
!cmake --build build --config Release --target llama-cli -j$(nproc)

!ls /content/BitNet/build/bin

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

# 1. Place your GGUF file into the official model directory structure
!mkdir -p models/BitNet-b1.58-2B-4T
!cp /content/ggml-model-i2_s.gguf models/BitNet-b1.58-2B-4T/

# 2. Fix the known Clang compiler bug in ggml-bitnet-mad.cpp (missing const qualifier)
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Ensure the LUT kernel header exists
!mkdir -p include
!cp preset_kernels/BitNet-b1.58-2B-4T/bitnet-lut-kernels-tl2.h include/bitnet-lut-kernels.h 2>/dev/null || touch include/bitnet-lut-kernels.h

# 4. Clean previous build and reconfigure with CLI targets enabled
!rm -rf build
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DBITNET_X86_TL2=OFF \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_TOOLS=ON

# 5. Compile llama-cli explicitly
!cmake --build build --config Release --target llama-cli -j$(nproc)

# 6. Verify the binary exists
!ls -lh build/bin/llama-cli

"""https://huggingface.co/tiiuae/Falcon3-10B-Instruct-GGUF

https://huggingface.co/HF1BitLLM/Llama3-8B-1.58-100B-tokens/tree/main
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

# 1. Place the model file in the preset path expected by setup_env.py
!mkdir -p models/BitNet-b1.58-2B-4T
!cp /content/ggml-model-i2_s.gguf models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf

# 2. Patch the known Clang bug in ggml-bitnet-mad.cpp (missing const qualifier)
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Completely wipe the dirty build cache
!rm -rf build

# 4. Run the official setup script (it will configure CMake and compile llama-cli)
!python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s

# 5. Confirm the binary was successfully created
!ls -lh build/bin/llama-cli

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet
!python run_inference.py -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

# Compile only llama-cli using all available CPU threads
!cmake --build build --config Release --target llama-cli -j$(nproc)

# Verify the binary is ready
!ls -lh build/bin/llama-cli

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet
import os

# Ensure shared libraries are discoverable
os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "You are a helpful assistant" \
    -cnv

# Run inference with the quantized model
!python run_inference.py -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 100 \
    --temp 0.7 \
    --repeat-penalty 1.15

!python run_inference.py -h

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/BitNet

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 100 \
    -temp 0.7

"""https://aistudio.google.com/prompts/1a9QXmKEXl3nCqNx6HEjlGp6rL86RnQCJ"""

# Commented out IPython magic to ensure Python compatibility.
Fixing BitNet Inference Errors
44,146 tokens

User 3:42 AM
https://github.com/microsoft/BitNet
# %cd BitNet
Run inference with the quantized model
!python /content/BitNet/run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
[Errno 2] No such file or directory: 'BitNet'
/content/BitNet
Traceback (most recent call last):
File "/content/BitNet/run_inference.py", line 55, in <module>
run_inference()
~~~~~~~~~~~~~^^
File "/content/BitNet/run_inference.py", line 36, in run_inference
run_command(command)
~~~~~~~~~~~^^^^^^^^^
File "/content/BitNet/run_inference.py", line 11, in run_command
subprocess.run(command, shell=shell, check=True)
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/subprocess.py", line 555, in run
with Popen(*popenargs, **kwargs) as process:
~~~~~^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/subprocess.py", line 1040, in init
self._execute_child(args, executable, preexec_fn, close_fds,
~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pass_fds, cwd, env,
^^^^^^^^^^^^^^^^^^^
...<5 lines>...
gid, gids, uid, umask,
^^^^^^^^^^^^^^^^^^^^^^
start_new_session, process_group)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/subprocess.py", line 1877, in _execute_child
self._posix_spawn(args, executable, env, restore_signals, close_fds,
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p2cread, p2cwrite,
^^^^^^^^^^^^^^^^^^
c2pread, c2pwrite,
^^^^^^^^^^^^^^^^^^
errread, errwrite)
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.13/subprocess.py", line 1821, in _posix_spawn
self.pid = os.posix_spawn(executable, args, env, **kwargs)
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'build/bin/llama-cli'
Model 3:42 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The errors occur for two reasons:
[Errno 2] No such file or directory: 'BitNet': You ran %cd BitNet when either the directory had not been cloned yet, or you were already inside the /content/BitNet directory.
FileNotFoundError: ... 'build/bin/llama-cli': run_inference.py is a Python wrapper that executes the compiled C++ binary (build/bin/llama-cli)[1][2]. You haven't built/compiled the project yet[1][3].
Step-by-Step Fix for Google Colab
Run these cells in order in your Colab notebook:
1. Reset directory and clone BitNet (with submodules)
BitNet relies on submodules (like llama.cpp), so you must clone with --recursive[3][4][5]:
code
Python
# %cd /content
!rm -rf BitNet  # Clean up in case of a partial or corrupted clone
!git clone --recursive https://github.com/microsoft/BitNet.git
# %cd /content/BitNet
2. Install dependencies & build tools
BitNet requires clang, cmake, and the Python packages[6][7]:
code
Python
!apt-get update && apt-get install -y clang cmake
!pip install -r requirements.txt
3. Compile the BitNet binary (llama-cli)
You need to compile the C++ binaries. You can do this using BitNet's automated setup script or via CMake directly[2][4][7].
Option A (Recommended — BitNet setup script):
code
Python
# This configures the kernels, runs CMake, and creates build/bin/llama-cli
!python setup_env.py -q i2_s
Option B (Manual CMake build):
code
Python
!cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
!cmake --build build --config Release -j$(nproc)
(Once complete, verify that /content/BitNet/build/bin/llama-cli exists[2][8]).
4. Run inference
Now that the binary is compiled, run inference with your model[8][9]:
code
Python
# %cd /content/BitNet
!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Sources
help
github.com
github.com
dev.to
github.com
datacamp.com
kdnuggets.com
github.com
huggingface.co
kdnuggets.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:44 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
This error occurs because setup_env.py expects a specific pre-defined model name (either through --hf-repo or -md)[1].
When you run python setup_env.py -q i2_s without a valid model specified:
It tries to look for pre-tuned kernel files inside preset_kernels/<model-name>[2].
Because no model was specified, it defaults to the unhandled code-generation branch in gen_code(), which contains raise NotImplementedError()[2][3].
Additionally, setup_env.py attempts to download and re-convert weights from Hugging Face, which is unnecessary since you already have the .gguf file (/content/ggml-model-i2_s.gguf).
Solution: Build directly with CMake
For i2_s quantization, you only need CMake to compile build/bin/llama-cli. BitNet's CMake setup expects include/bitnet-lut-kernels.h to exist, so ensure that file is present (or create an empty dummy header) before compiling:
1. Prepare headers and build with CMake
Run this in a Colab cell:
code
Python
# %cd /content/BitNet

# Ensure the include directory and header exist so CMake won't complain
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# Generate build files and compile llama-cli
!cmake -B build
!cmake --build build --config Release -j$(nproc)
2. Verify the binary was created
code
Python
!ls -lh build/bin/llama-cli
(You should see the compiled llama-cli executable).
3. Run inference
Now execute run_inference.py using your pre-downloaded GGUF file:
code
Python
# %cd /content/BitNet
!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Sources
help
github.com
github.com
scribd.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:50 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The directory currently contains only the shared libraries (libggml.so, libllama.so, etc.)[1][2]. The actual executable llama-cli was not built[2][3].
Why this happens
Because llama.cpp is included as a submodule inside BitNet, CMake turns off CLI executables by default (LLAMA_BUILD_EXAMPLES=OFF) unless told otherwise[3]. Without this flag, CMake only compiles the core .so shared libraries[2][3].
How to build llama-cli
Reconfigure CMake with -DLLAMA_BUILD_EXAMPLES=ON and build the llama-cli target[4][5]:
code
Python
# %cd /content/BitNet

# 1. Ensure required header stub exists
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# 2. Configure CMake with examples/CLI tools enabled
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_TOOLS=ON

# 3. Explicitly build the llama-cli target
!cmake --build build --config Release --target llama-cli -j$(nproc)
Verify the binary is there:
code
Python
!ls -lh build/bin/llama-cli
You should now see the llama-cli executable inside build/bin/[6][7].
Run inference:
code
Python
# %cd /content/BitNet
!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Sources
help
esso.dev
github.com
github.com
huggingface.co
github.com
github.com
medium.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:50 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The error still occurs because the CMake build failed to produce llama-cli, likely due to two known issues in the BitNet repository:
A compiler type mismatch bug in src/ggml-bitnet-mad.cpp (line 811)[1][2]: Clang fails with error: cannot initialize a variable of type 'int8_t *' with an rvalue of type 'const int8_t *'. When this occurs, compilation terminates before llama-cli is linked.
Preset naming in setup_env.py[1][3]: BitNet expects the model directory to be named after one of its presets (e.g., models/BitNet-b1.58-2B-4T) to load the architecture config and avoid NotImplementedError.
Complete Colab Fix
Run the following cell to patch the source bug, configure the preset directory, compile the binary, and verify the build:
code
Python
# %cd /content/BitNet

# 1. Place your GGUF file into the official model directory structure
!mkdir -p models/BitNet-b1.58-2B-4T
!cp /content/ggml-model-i2_s.gguf models/BitNet-b1.58-2B-4T/

# 2. Fix the known Clang compiler bug in ggml-bitnet-mad.cpp (missing const qualifier)
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Ensure the LUT kernel header exists
!mkdir -p include
!cp preset_kernels/BitNet-b1.58-2B-4T/bitnet-lut-kernels-tl2.h include/bitnet-lut-kernels.h 2>/dev/null || touch include/bitnet-lut-kernels.h

# 4. Clean previous build and reconfigure with CLI targets enabled
!rm -rf build
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DBITNET_X86_TL2=OFF \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_TOOLS=ON

# 5. Compile llama-cli explicitly
!cmake --build build --config Release --target llama-cli -j$(nproc)

# 6. Verify the binary exists
!ls -lh build/bin/llama-cli
Run Inference
Once the build prints [100%] Built target llama-cli and ls confirms build/bin/llama-cli exists, run:
code
Python
# %cd /content/BitNet

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "You are a helpful assistant" \
    -cnv
Sources
help
kdnuggets.com
github.com
globalaiforce.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:52 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
What happened
Notice these two lines in your CMake log:
code
Text
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
CMake detected that the compiler changed (from GCC to Clang) in an existing build folder. When CMake resets its cache like that, it wipes all custom flags (including -DLLAMA_BUILD_EXAMPLES=ON). Without that flag, CMake only generates the library targets and completely skips llama-cli[1][2]—hence:
code
Text
gmake: *** No rule to make target 'llama-cli'. Stop.
The Clean Solution
Now that the requirements are clear, we can let BitNet's setup_env.py handle the build properly[3]. By placing your .gguf file into models/BitNet-b1.58-2B-4T/:
setup_env.py recognizes the model architecture[4][5].
It detects that the GGUF file already exists, so it skips downloading and conversion[6][7].
It sets all the correct CMake flags (-DLLAMA_BUILD_EXAMPLES=ON, etc.) automatically[8].
Run this in a single cell:
code
Python
# %cd /content/BitNet

# 1. Place the model file in the preset path expected by setup_env.py
!mkdir -p models/BitNet-b1.58-2B-4T
!cp /content/ggml-model-i2_s.gguf models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf

# 2. Patch the known Clang bug in ggml-bitnet-mad.cpp (missing const qualifier)
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Completely wipe the dirty build cache
!rm -rf build

# 4. Run the official setup script (it will configure CMake and compile llama-cli)
!python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s

# 5. Confirm the binary was successfully created
!ls -lh build/bin/llama-cli
Run Inference
Once the build completes and build/bin/llama-cli is confirmed[9], run:
code
Python
# %cd /content/BitNet
!python run_inference.py -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Sources
help
github.com
github.com
kdnuggets.com
github.com
github.com
github.com
github.com
github.com
github.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:52 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The issue is a known bug in BitNet's top-level CMakeLists.txt[1][2].
Because llama.cpp is included as a Git submodule, CMake sets LLAMA_STANDALONE=OFF and disables all CLI tools and examples by default[1][3]. The top-level BitNet/CMakeLists.txt forgets to force-enable LLAMA_BUILD_EXAMPLES and LLAMA_BUILD_COMMON[1][4]. As a result, the compiler only generates the shared libraries (.so) and never creates llama-cli[1].
The Complete Fix
Run the following cell to patch CMakeLists.txt and src/ggml-bitnet-mad.cpp, rebuild, and generate llama-cli:
code
Python
# %cd /content/BitNet

# 1. Patch BitNet's CMakeLists.txt to force build CLI tools and examples
!sed -i 's/set(LLAMA_BUILD_SERVER ON CACHE BOOL "Build llama.cpp server" FORCE)/set(LLAMA_BUILD_SERVER ON CACHE BOOL "Build llama.cpp server" FORCE)\nset(LLAMA_BUILD_COMMON ON CACHE BOOL "Build common" FORCE)\nset(LLAMA_BUILD_EXAMPLES ON CACHE BOOL "Build examples" FORCE)/' CMakeLists.txt

# 2. Fix the Clang pointer mismatch in ggml-bitnet-mad.cpp (line 811)
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Create dummy header stub required by the build
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# 4. Remove previous build cache completely
!rm -rf build

# 5. Configure and build
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DBITNET_X86_TL2=OFF
!cmake --build build --config Release -j$(nproc)

# 6. Verify that llama-cli is now built
!ls -lh build/bin/llama-cli
Run Inference
Once ls -lh build/bin/llama-cli shows the binary, set LD_LIBRARY_PATH (so Linux can find the .so files at runtime)[5][6] and run your model:
code
Python
# %cd /content/BitNet
import os

# Set library search path to find libllama.so and libggml.so
os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Sources
help
github.com
github.com
github.com
github.com
esso.dev
github.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
Model 3:54 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The error occurred because sed failed to patch the submodule flags silently, so CMake still evaluated LLAMA_BUILD_TOOLS=OFF and LLAMA_BUILD_EXAMPLES=OFF. In that state, CMake only generates targets for the .so shared libraries and never defines llama-cli.
Passing those flags directly into the cmake command ensures CMake includes the CLI targets.
Run this cell to build llama-cli:
code
Python
# %cd /content/BitNet

# 1. Ensure submodules are fully synced
!git submodule update --init --recursive

# 2. Fix the known Clang bug in ggml-bitnet-mad.cpp
!sed -i 's/int8_t \* y_col/const int8_t * y_col/g' src/ggml-bitnet-mad.cpp

# 3. Create dummy kernel header stub expected by CMake
!mkdir -p include
!touch include/bitnet-lut-kernels.h

# 4. Install OpenMP for multi-core acceleration (optional but recommended)
!apt-get install -y libomp-dev

# 5. Clean build directory completely
!rm -rf build

# 6. Configure CMake with CLI/tools explicitly enabled
!cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DBITNET_X86_TL2=OFF \
    -DLLAMA_BUILD_COMMON=ON \
    -DLLAMA_BUILD_TOOLS=ON \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_SERVER=ON

# 7. Compile all targets
!cmake --build build --config Release -j$(nproc)

# 8. Check that llama-cli exists
!ls -lh build/bin/llama-cli
Run Inference
Once the build finishes and shows build/bin/llama-cli, run:
code
Python
# %cd /content/BitNet
import os

# Ensure the system loader finds libllama.so and libggml.so
os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!python run_inference.py -m /content/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
Model 4:07 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The script is not broken—it is compiling sequentially on a single CPU thread (-j1) and buffering output, which makes it look frozen.
By default, setup_env.py does not pass parallel flags and compiles every single example, benchmark, and test in llama.cpp. On Colab's virtual CPU, this can take 15–20 minutes without showing real-time progress.
How to Speed This Up
1. Stop the hanging cell
Click the Stop / Interrupt button (⏹️) next to the currently running cell in Colab.
2. Build in parallel (Takes ~1–2 minutes)
Since setup_env.py already finished generating the build configuration, compile only the required target (llama-cli) using all CPU cores with live progress:
code
Python
# %cd /content/BitNet

# Compile only llama-cli using all available CPU threads
!cmake --build build --config Release --target llama-cli -j$(nproc)

# Verify the binary is ready
!ls -lh build/bin/llama-cli
You will see live percentage output (e.g., [ 15%] Building CXX object..., [100%] Built target llama-cli).
3. Run Inference
Once llama-cli is compiled, run inference with your model:
code
Python
# %cd /content/BitNet
import os

# Ensure shared libraries are discoverable
os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "You are a helpful assistant" \
    -cnv
Model 4:11 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
The build succeeded and the model loaded.
There are two details in the output to understand:
1. The GPU Warning is Expected
code
Text
warning: no usable GPU found, --gpu-layers option will be ignored
BitNet b1.58 is designed to run on CPUs. Its ternary weights (
−
1
,
0
,
1
−1,0,1
) replace expensive matrix multiplication with integer addition and subtraction, allowing CPU inference without requiring a dedicated GPU.
2. Why it repeated in an infinite loop
BitNet-b1.58-2B-4T is a base foundation model, not an instruction/chat-tuned model (unlike ChatGPT or Llama-Instruct).
Base models are pure text auto-completers:
When given a system prompt like "You are a helpful assistant" inside conversation mode (-cnv), it does not recognize an instruction format and falls into a repetitive token loop.
Because -cnv defaults to an artificial Human: / AI: exchange, an untuned base model easily echoes the pattern endlessly.
How to Run it Correctly
Option A: Text Completion (Recommended for Base Models)
Drop -cnv and provide a prompt meant to be completed (like the beginning of a sentence, article, or question). Add --repeat-penalty and a token limit (-n):
code
Python
# %cd /content/BitNet

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 100 \
    --temp 0.7 \
    --repeat-penalty 1.15
Option B: Few-Shot Prompting (For Q&A / Chat)
Since base models learn from patterns, you can guide it using 1–2 examples (few-shot prompting) instead of direct commands:
code
Python
# %cd /content/BitNet

few_shot_prompt = """Q: What is the capital of France?
A: The capital of France is Paris.

Q: What is photosynthesis?
A:"""

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "{few_shot_prompt}" \
    -n 64 \
    --temp 0.5 \
    --repeat-penalty 1.2
Option C: Interactive Mode with Stop Tokens
If you want to chat interactively with -cnv, pass a reverse stop token (-r "Human:") so it stops generating when it expects your turn:
code
Python
# %cd /content/BitNet

!build/bin/llama-cli \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "A conversation between a curious user and an intelligent assistant.\n\nUser: Hello!\nAssistant: Hi there! How can I help you today?\nUser:" \
    -cnv \
    -r "User:" \
    --repeat-penalty 1.2 \
    --temp 0.7
Model 4:13 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
run_inference.py is a simple wrapper script that only exposes a subset of flags (notice that it also uses -temp instead of --temp, and it notes: -cnv is only for instruct models).
Option 1: Using run_inference.py (Valid flags only)
Since this is a base model, omit -cnv and use only the supported flags (-m, -p, -n, -temp, -c):
code
Python
# %cd /content/BitNet

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 100 \
    -temp 0.7
For Q&A, you can use a completion prompt:
code
Python
# %cd /content/BitNet

prompt = "Question: What is the capital of France?\nAnswer:"

!python run_inference.py \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "{prompt}" \
    -n 50 \
    -temp 0.3
Option 2: Calling build/bin/llama-cli directly (Recommended for full control)
run_inference.py just calls build/bin/llama-cli behind the scenes. If you call llama-cli directly, you gain access to all standard llama.cpp features, including:
--repeat-penalty (prevents looping)
--top-p and --top-k
-r (stop tokens)
code
Python
# %cd /content/BitNet
import os

# Set library search path
os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!build/bin/llama-cli \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 100 \
    --temp 0.7 \
    --repeat-penalty 1.15
Model 4:16 AM
ThinkingThoughts
Expand to view model thoughts

chevron_right
معك حق تماماً، والنتيجة التي تراها ليست خطأ منك، بل ترجع لسببين رئيسيين يتعلقان بطبيعة هذا النموذج تحديداً:
لماذا ظهر النموذج بهذا السوء ووقع في حلقة تكرار؟
نموذج خام تجريبي (Base Model) وليس نموذج محادثة (Instruct/Chat):
نموذج BitNet-b1.58-2B-4T ليس مصمماً للدردشة أو فهم الأوامر مثل ChatGPT[1][2]. هو مجرد نموذج بحثي تجريبي (Proof of Concept) أطلقته مايكروسوفت لإثبات إمكانية تشغيل الشبكات بـ 1.58 بت على المعالج[3][4][5].
لم يمر النموذج بمرحلة تدريب على التعليمات (Fine-tuning / RLHF)، لذلك عند إعطائه أي جملة يحاول التنبؤ بالحرف التالي فيفشل ويدخل في حلقة تكرار لا نهائية[6].
وضع المحادثة (-cnv) ما زال مفعلاً:
تلاحظ في المخرجات علامة > وقائمة الأوامر، مما يعني أنك شغلته بوضع المحادثة التفاعلية -cnv.
في هذا الوضع، يحاول llama-cli محاكاة دردشة بشرية، وهو ما يربك النماذج الخام التي لا تفهم سياق الردود.
تأثير الضغط الفائق (1.58-bit):
تقليص نموذج صغير (2 مليار معامل فقط) إلى أوزان ثنائية/ثلاثية (1.58 بت) يفقده جزءاً ضخماً من ترابطه اللغوي ما لم يتم ضبط معايير مثل مانع التكرار (--repeat-penalty).
تجربة النموذج بالطريقة الصحيحة (إيقاف التكرار)
لكسر حلقة التكرار، يجب تشغيل أمر llama-cli مباشرة بدون وضع المحادثة (-cnv) ومع تفعيل مانع التكرار --repeat-penalty:
code
Python
# %cd /content/BitNet
import os

os.environ["LD_LIBRARY_PATH"] = f"/content/BitNet/build/bin:/content/BitNet/build/3rdparty/llama.cpp/src:/content/BitNet/build/3rdparty/llama.cpp/ggml/src:{os.environ.get('LD_LIBRARY_PATH', '')}"

!build/bin/llama-cli \
    -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf \
    -p "The theory of relativity states that" \
    -n 80 \
    --temp 0.7 \
    --repeat-penalty 1.25
البديل الحقيقي: إذا أردت نموذجاً ذكياً وسريعاً جداً على الـ CPU
إذا كان هدفك استخدام نموذج صغير الحجم، سريع على المعالج (CPU)، وممتاز جداً في العربية والإنجليزية، فإن مجتمع المصدر المفتوح تجاوز BitNet بفضل نماذج Q4 (4-bit) التي تقدم ذكاءً أعلى بمراحل.
أفضل مثال هو Qwen2.5-1.5B-Instruct أو Qwen2.5-3B-Instruct:
حجمه ~1.5 إلى 2 جيجابايت فقط.
مخصص ومدرّب على المحادثة والإجابة عن الأسئلة بدقة عالية وباللغة العربية.
يعمل على الـ CPU بنفس السرعة دون مشاكل التكرار.
Sources
help
medium.com
deepwiki.com
esso.dev
github.com
github.com
reddit.com
Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
info
Google AI models may make mistakes, so double-check outputs.